# Generated by Django 3.2.13 on 2022-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=100)),
                ('data_de_publicacao', models.DateTimeField()),
                ('done', models.CharField(choices=[(1, 'Fazendo'), (2, 'Feito')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('sexo', models.CharField(max_length=10)),
                ('idade', models.IntegerField()),
                ('profissao', models.CharField(max_length=200)),
                ('done', models.CharField(choices=[(1, 'Fazendo'), (2, 'Feito')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
